#!perl
=head1 NAME

  Vacations module

=cut


use strict;
use warnings FATAL => 'all';

use Vacations::db::Vacations;
use Abills::Base qw/_bp sendmail/;

our(
  %lang,
  $html,
  $admin,
  $user,
  $db,
  %conf,
  @MODULES,
);

my $Vacations = Vacations->new($db, $admin, \%conf);
my $User = Users->new($db, $admin, \%conf);
my @lastday = (31,28,31,30,31,30,31,31,30,31,30,31);
my @months = ("січня", "лютого", "березня", "квітня", "травня", "червня", "липня", "серпня", "вересня", "жовтня", "листопада", "грудня");

#**********************************************************
=head2 vacations_user_info($attr)

=cut
#**********************************************************
sub vacations_user_info {
  
  if ($FORM{first_login} && $FORM{passwd} && $FORM{user}) {
    $html->message('info', $lang{INFO}, "Ваш логин: $FORM{user}\nВаш пароль: $FORM{passwd}");
  }

  $Vacations->info($user->{UID});
  
  if ($FORM{CHANGE_PASSWORD} || $FORM{newpassword}) {
    form_passwd();
  }
  elsif ($FORM{VCT_END}) {
    $Vacations->{VCT_START} = $FORM{VCT_START};
    $Vacations->{VCT_END} = $FORM{VCT_END};
    $Vacations->{FIO} = "$Vacations->{SURNAME} $Vacations->{NAME} $Vacations->{MID_NAME}";
    
    $Vacations->{VCT_START_DAY} = _date_to_str($FORM{VCT_START});
    $Vacations->{DATE} = _date_to_str($DATE);
    
    $Vacations->{VCT_DAYS} = _period_days($FORM{VCT_START}, $FORM{VCT_END});
    
    my $holidays = $Vacations->holidays({ WORKDAY => '2', INTERVAL => "$FORM{VCT_START}/$FORM{VCT_END}" });
    $Vacations->{HOLYDAYS} = 0;
    $Vacations->{HOLYDAYS} = scalar @$holidays if (ref $holidays eq 'ARRAY');
    my $days_used = $Vacations->{VCT_DAYS} - $Vacations->{HOLYDAYS};
    $Vacations->{VCT_USE_DAYS} = $days_used;
    
    my $periods_list = vct_periods({ NO_PRINT => 1});
    my $periods_text = "";
    foreach (@$periods_list) {
      my $days_in_period = $_->{days_accrued} - $_->{days_used};
      next unless ($days_in_period);
      if ($days_in_period >= $days_used ) {
        $periods_text .= "$_->{start_period} - $_->{end_period} : $days_used";
        last;
      }
      else {
        $periods_text .= "$_->{start_period} - $_->{end_period} : $days_in_period,<br>";
        $days_used -= $days_in_period;
      }
    }
    $Vacations->{PERIODS} = $periods_text;
    
    
    
    $html->tpl_show(_include('vacations_print', 'Vacations'), $Vacations);
    return 1;
  }
  elsif ($FORM{VCT_START}) {
    $Vacations->{VCT_START} = $FORM{VCT_START};
    $Vacations->{DATEPICKER1} = "<div class='col-md-6' id='datepicker3'></div>";
    $Vacations->{DATEPICKER2} = "<div class='col-md-6' id='datepicker2'></div>";
    $Vacations->{BUTTON2} = "<input type=submit name='next' value='Дальше' class='btn btn-primary'>";
  
    my $not_av_dates = _not_available_dates($FORM{VCT_START});
    my $holidays = $Vacations->holidays({ WORKDAY => '2'});
    foreach (@$holidays) {
      $Vacations->{DISABLE_DATES} .= "'$_->{date}', ";
    }
    $Vacations->{DISABLE_DATES} .= $not_av_dates;
    $Vacations->{STARTD} = $FORM{VCT_START};
    $Vacations->{END} = _add_days($FORM{VCT_START}, $Vacations->{TOTAL_DAYS_LEFT} );
    $html->tpl_show(_include('vacations_date_select', 'Vacations'), $Vacations);
    return 1;
  }
  elsif ($FORM{VACATION_REQUEST}) {
    $Vacations->{DATEPICKER1} = "<div class='col-md-6' id='datepicker1'></div>";
    $Vacations->{BUTTON1} = "<input type=submit name='next' value='Дальше' class='btn btn-primary'>";
    my $holidays = $Vacations->holidays({ WORKDAY => '0'});
    $Vacations->{DISABLE_DATES} = '';
    $Vacations->{STARTD} = $DATE;
    $Vacations->{END} = _add_days($DATE, 30);
    foreach (@$holidays) {
      $Vacations->{DISABLE_DATES} .= "'$_->{date}', ";
    }
    $html->tpl_show(_include('vacations_date_select', 'Vacations'), $Vacations);
    return 1;
  }

  if($Vacations->{ROLE} < 1) {
    $html->message('warn', $lang{WARNING}, "Ваш доступ заблокирован. Обратитесь к администратору.");
    return 1;
  }
  my $av_days = _available_vacation_length();
  foreach (@$av_days) {
    $Vacations->{AVAIABLE_LENGTH} .= "$_, ";
    if ($_ > 31) {
      $Vacations->{AVAIABLE_LENGTH} .= " ... @$av_days[-1]";
      last;
    }
  }
  $Vacations->{AVAIABLE_LENGTH} =~ s/,\s$//;
  $Vacations->{CHANGE_PASSWORD} = $html->button($lang{CHANGE_PASSWORD}, "index=10&CHANGE_PASSWORD=1&sid=$sid", { class => 'btn btn-sm btn-primary' });
  $Vacations->{VACATION_REQUEST} = $html->button("Заявление о предоставлении отпуска", "index=10&VACATION_REQUEST=1&sid=$sid", { class => 'btn btn-block btn-success' });
  $html->tpl_show(_include('vacations_user_info', 'Vacations'), $Vacations);

  return 1;
}

#**********************************************************
=head2 vacations_registration($attr)

=cut
#**********************************************************
sub vacations_registration {
  
  if ( $FORM{reg} ) {
    if (!$FORM{EMAIL} || $FORM{EMAIL} !~ /^(([^<>()[\]\\.,;:\s\@\"]+(\.[^<>()[\]\\.,;:\s\@\"]+)*)|(\".+\"))\@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/) {
      $Vacations->{MESSAGE} = $html->message('err', $lang{ERROR}, "$lang{ERR_WRONG_EMAIL}");
    }
    elsif ($FORM{TID}) {
      my $main_info = $Vacations->main_info($FORM{TID});
      if ($Vacations->{TOTAL}) {
        $Vacations->{MESSAGE} = $html->message('warn', $lang{ERROR}, "Пользователь с табельным номером $FORM{TID} уже зарегистрирован.");
      }
      else {
        my $emp_info = $Vacations->emp_info($FORM{TID});
        if (!$Vacations->{TOTAL}) {
          $Vacations->{MESSAGE} = $html->message('warn', $lang{ERROR}, "Табельный номер $FORM{TID} не найден.");
        }
        else {
          if ( !$FORM{SURNAME} ) {
            $Vacations->{MESSAGE} = $html->message('warn', $lang{ERROR}, "Укажите вашу фамилию.");
          }
          elsif ($emp_info->[0]->{surname} ne $FORM{SURNAME}) {
            $Vacations->{MESSAGE} = $html->message('warn', $lang{ERROR}, "Фамилия и табельный номер не совпадают.");
          }
          else {
            my $password = mk_unique_value($conf{PASSWD_LENGTH} || 6, { EXTRA_RULES => '0:0' });
            $User->add({ LOGIN => $FORM{EMAIL}, PASSWORD => $password });
            _error_show($User);

            my $uid = $User->{INSERT_ID};
    
            if ( $User->{errno} ) {
              $html->message('err', "$lang{ERROR}", "Ошибка при создании пользователя $FORM{TID}");
              return 0;
            }

            $User->pi_add({ UID => $uid, EMAIL => $FORM{EMAIL} });
            _error_show($User);

            $Vacations->user_add({ TID => $FORM{TID}, UID => $uid });
            _error_show($Vacations);

            if ( $Vacations->{errno} ) {
              $html->message('err', "$lang{ERROR}", "Обратитесь к администратору.");
            }
            else {
              $html->message('info', "$lang{SUCCESS}", "Пользователь $FORM{TID} успешно зарегистрирован.");
              my $login_url = $SELF_URL;
              $login_url =~ s/registration/index/;
              print "Location: $login_url?user=$FORM{TID}&passwd=$password&first_login=1\n\n";
              return 1;
            }
          }
        }

      }
    }
    else {
      $Vacations->{MESSAGE} = $html->message('warn', $lang{ERROR}, "Укажите табельный номер.");
    }
  }

  $html->tpl_show(_include('vacations_user_registration', 'Vacations'), { %{$Vacations}, %FORM }, { ID => 'VACATIONS_REGISTRATION' });
  

  return 1;
}


#**********************************************************
=head2 orders_import($attr)

=cut
#**********************************************************
sub orders_import {
  my $filename = '/usr/abills/var/datain/vacation_orders.csv';
  my @ColumnNames = ('TID', 'ORDER_ID', 'ORDER_DATE', 'VCT_START', 'VCT_END', 'VCT_DAYS', 'USED');

  $Vacations->truncate_table('vacations_orders');

  open FILE, "< $filename" or die  "Can't open $filename : $!";

  my $columns = <FILE>;

  while (<FILE>) {
    chomp $_;
    my %hash;
    @hash{@ColumnNames} = split (';');
    $hash{ORDER_DATE} = _str_to_date($hash{ORDER_DATE});
    $hash{VCT_START} = _str_to_date($hash{VCT_START});
    $hash{VCT_END} = _str_to_date($hash{VCT_END});

    $Vacations->add('vacations_orders', \%hash);
    _error_show($Vacations);
  }

  close FILE;
  return 1;

}

#**********************************************************
=head2 holidays_import($attr)

=cut
#**********************************************************
sub holidays_import {
  my $filename = '/usr/abills/var/datain/Holidays.csv';
  my @ColumnNames = ('DATE', 'WORKDAY');

  $Vacations->truncate_table('vacations_holidays');

  open FILE, "< $filename" or die  "Can't open $filename : $!";

  my $columns = <FILE>;

  while (<FILE>) {
    chomp $_;
    my %hash;
    @hash{@ColumnNames} = split (';');
    $hash{DATE} = _str_to_date($hash{DATE});

    $Vacations->add('vacations_holidays', \%hash);
    _error_show($Vacations);
  }

  close FILE;
  return 1;

}

#**********************************************************
=head2 accrued_import($attr)

=cut
#**********************************************************
sub accrued_import {
  my $filename = '/usr/abills/var/datain/vacation_acrule_periods.csv';
  my @ColumnNames = ('TID', 'START_PERIOD', 'END_PERIOD', 'DAYS_ACCRUED', 'DAYS_USED');

  $Vacations->truncate_table('vacations_accrued_periods');

  open FILE, "< $filename" or die  "Can't open $filename : $!";

  my $columns = <FILE>;

  while (<FILE>) {
    chomp $_;
    my %hash;
    @hash{@ColumnNames} = split (';');
    $hash{START_PERIOD} = _str_to_date($hash{START_PERIOD});
    $hash{END_PERIOD} = _str_to_date($hash{END_PERIOD});

    $Vacations->add('vacations_accrued_periods', \%hash);
    _error_show($Vacations);
  }

  close FILE;
  return 1;

}

#**********************************************************
=head2 orders_import($attr)

=cut
#**********************************************************
sub employees_import {
  my $filename = '/usr/abills/var/datain/employees.csv';
  my @ColumnNames = ('TID', 'SURNAME', 'NAME', 'MID_NAME', 'SURNAME_GENETIVE', 'START_DATE', 'POSITION', 'VCT_DAYS', 'COMPANY', 'VCT_LEFT');

  $Vacations->truncate_table('vacations_employees');

  open FILE, "< $filename" or die  "Can't open $filename : $!";

  my $columns = <FILE>;

  while (<FILE>) {
    chomp $_;
    my %hash;
    @hash{@ColumnNames} = split (';');
    $hash{START_DATE} = _str_to_date($hash{START_DATE});

    $Vacations->add('vacations_employees', \%hash);
    _error_show($Vacations);
  }

  close FILE;
  return 1;

}

#**********************************************************
=head2 _str_to_date($attr)

convert 01.02.17 to 2017-02-01

=cut
#**********************************************************
sub _str_to_date {
  my ($str) = @_;
  return "20" . join '-', reverse split '\.', $str;
}

#**********************************************************
=head2 _date_to_str($date)

convert 01.02.17 to 2017-02-01

=cut
#**********************************************************
sub _date_to_str {
  my ($date) = @_;
  
  my ($year, $month, $day) = split '-', $date;
  
  return "\«$day\» $months[$month-1] $yearр.";
}

#**********************************************************
=head2 _not_available_dates($start_date)

return array of dates not available for end vacation

=cut
#**********************************************************
sub _not_available_dates {
  my ($date) = @_;
  my $av_len = _available_vacation_length();
  
  my $lenght = 1;
  my $counter = 0;
  my $date_list = '';
  my $holidays = $Vacations->holidays({ WORKDAY => '2'});
  my %holyhash = ();
  foreach (@$holidays) {
    $holyhash{$_->{date}} = 1;
  }
  
  while ($lenght <= @$av_len[-1] ) {
    if (!$holyhash{$date}) {
      if ( $lenght == $av_len->[$counter]) {
        $counter++;
      }
      else {
        $date_list .= "'$date', ";
      }
      $lenght++;
    }
    $date = _add_days($date, 1);
  }
  return $date_list;
}

#**********************************************************
=head2 _available_vacation_length()

return array of avaiable vacations

=cut
#**********************************************************
sub _available_vacation_length {
  $Vacations->info($user->{UID});
  my $periods_list = vct_periods({ NO_PRINT => 1});

  my @periods = ();
  my @avaiable_length = ();

  foreach (@$periods_list) {
    push @periods, ($_->{days_accrued} - $_->{days_used});
  }

  if ( @periods < 1 ) {
    @avaiable_length = (1 .. 32);
    return \@avaiable_length;
  }

  while (@periods > 0 && $periods[0] == 0) {
    shift @periods;
  }

  if ( @periods < 1 ) {
    return [ ];
  }

  if ( $periods[0] < 14 ) {
    @avaiable_length = (1 .. $periods[0])
  }
  elsif ( $periods[0] == 14 ){
    @avaiable_length = (14);
  }
  elsif ( $periods[0] < 28 ) {
    @avaiable_length = (1 .. ($periods[0] - 14), 14 .. $periods[0]) ;
  }
  else {
     @avaiable_length = (1 .. $periods[0]);
  }

  if ( @periods > 1) {
    my $unused_days = 0;
    foreach (2 .. @periods)  {
      $unused_days += $periods[$_ - 1];
    }
    push  @avaiable_length, (($periods[0] + 1) .. ($periods[0] + $unused_days + 16)); 
  }

  return \@avaiable_length;
}



#**********************************************************
=head2 vct_history($attr)

=cut
#**********************************************************
sub vct_history {
  
  $Vacations->info($user->{UID});
  if($Vacations->{ROLE} < 1) {
    $html->message('warn', $lang{WARNING}, "Ваш доступ заблокирован. Обратитесь к администратору.");
    return 1;
  }

  my $vct_list = $Vacations->orders_list($Vacations->{TID});

  my $table = $html->table({
    width         => '100%',
    caption       => "История отпусков",
    border        => 1,
    title_plain   => [ "Приказ №", "Дата приказа", "Начало отпуска", "Конец отпуска", "Длительность отпуска" ],
    ID            => 'orders',
  });
  
  my $total_days = 0;

  foreach my $vct_line ( @$vct_list ) {
    $table->addrow($vct_line->{order_id}, $vct_line->{order_date}, $vct_line->{vct_start}, $vct_line->{vct_end}, $vct_line->{vct_days});
    $total_days += $vct_line->{vct_days};
  }
  
  $table->addrow("Всего:", '', '', '', $total_days );

  print $table->show();

  return 1;
}

#**********************************************************
=head2 vct_periods($attr)

=cut
#**********************************************************
sub vct_periods {
  my ($attr) = @_;

  $Vacations->info($user->{UID});
  if($Vacations->{ROLE} < 1) {
    $html->message('warn', $lang{WARNING}, "Ваш доступ заблокирован. Обратитесь к администратору.");
    return 1;
  }

  # my $periods_list = $Vacations->periods_list($Vacations->{TID});

  my $table = $html->table({
    width         => '100%',
    caption       => "Начисление отпусков",
    border        => 1,
    title_plain   => [ "Начало периода", "Конец периода", "Начислено отпускных дней", "Использовано отпускных дней" ],
    ID            => 'periods',
  });
  
  my $total_days_accrued = 0;

  # foreach my $period_line ( @$periods_list ) {
  #   $table->addrow($period_line->{start_period}, $period_line->{end_period}, $period_line->{days_accrued}, $period_line->{days_used});
  #   $total_days_used += $period_line->{days_used};
  #   $total_days_accrued += $period_line->{days_accrued};
  # }

  my $date = $Vacations->{START_DATE};
  my $periods_list = ();
  while (_add_years($date, 1) lt $DATE) {
    push (@$periods_list, { start_period => $date, end_period => _add_days(_add_years($date, 1), -1), days_accrued => 32 });
    $date = _add_years($date, 1);

    $total_days_accrued += 32;
  }
  
  push (@$periods_list, { start_period => $date, end_period => "$DATE", , days_accrued => 16 });
  $total_days_accrued += 32;
  
  my $total_days_used = $total_days_accrued - $Vacations->{TOTAL_DAYS_LEFT};
  my $days_used = 0;

  foreach my $period_line ( @$periods_list ) {
    $period_line->{days_used} = ($period_line->{days_accrued} > $total_days_used ) ? $total_days_used : $period_line->{days_accrued};
    $total_days_used -=  $period_line->{days_used};
    $table->addrow($period_line->{start_period}, $period_line->{end_period}, $period_line->{days_accrued}, $period_line->{days_used});
  }
  
  if ($attr->{NO_PRINT}) {
    return $periods_list;
  }


  $table->addrow("Всего:", '', $total_days_accrued, $total_days_accrued - $Vacations->{TOTAL_DAYS_LEFT} );

  print $table->show();
  
  return 1;
}

#**********************************************************
=head2 user_role($uid)

=cut
#**********************************************************
sub user_role {
  my ($uid) = @_;

  $Vacations->info($uid);

  return $Vacations->{ROLE} || -1;
}

#**********************************************************
=head2 vacation_log_add($uid)

=cut
#**********************************************************
sub vacation_log_add {
  my $self = shift;
  my ($attr) = @_;

  return  $Vacations->log_add($attr) || 0;
}


#**********************************************************
=head2 vacations_users_list()

=cut
#**********************************************************
sub vacations_users_list {

  my $u_role = user_role($user->{UID});
  
  if($FORM{DELETE} && $u_role == 3 ) {
    $Vacations->user_del($FORM{DELETE}, 'users_pi');
    $Vacations->user_del($FORM{DELETE}, 'vacations_main');
    $Vacations->user_del($FORM{DELETE}, 'users');
  }
  elsif($FORM{ROLE_2}) {
    $Vacations->user_change($FORM{ROLE_2}, '2');
  }
  elsif($FORM{ROLE_1}) {
    $Vacations->user_change($FORM{ROLE_1}, '1');
  }
  elsif($FORM{ENABLE}) {
    $Vacations->user_change($FORM{ENABLE}, '1');
  }
  elsif($FORM{DISABLE}) {
    $Vacations->user_change($FORM{DISABLE}, '0');
  }
  elsif($FORM{NEW_EMAIL}) {
    $User->pi_change({ UID => $FORM{CHG_EMAIL}, EMAIL => $FORM{NEW_EMAIL} });
    _error_show($User);
  }
  elsif($FORM{CHG_EMAIL}) {
    $Vacations->info($FORM{CHG_EMAIL});
    $html->tpl_show(_include('vacations_change_email', 'Vacations'), { %$Vacations, %FORM });
  }
  elsif($FORM{NEW_PSWD}) {
    $User->change($FORM{CHG_PSWD}, { UID => $FORM{CHG_PSWD}, PASSWORD => $FORM{NEW_PSWD} });
    if ($FORM{SEND_EMAIL}) {
      $Vacations->info($FORM{CHG_PSWD});
      my $message = "LOGIN: $Vacations->{TID}\nPASSWORD: $FORM{NEW_PSWD}";
      print $html->header();
      sendmail("$conf{ADMIN_MAIL}", "$Vacations->{EMAIL}", "Password Recovery", "$message", "$conf{MAIL_CHARSET}", "", {TEST => 1});
    }
  }
  elsif($FORM{CHG_PSWD}) {
    $Vacations->info($FORM{CHG_PSWD});
    $html->tpl_show(_include('vacations_change_pswd', 'Vacations'), { %$Vacations, %FORM });
  }

  my $user_list = $Vacations->users_list();
  
  my $table = $html->table({
    width         => '100%',
    caption       => "Список пользователей",
    border        => 1,
    title_plain   => [ "Табельный номер", "ФИО", "E-mail", "Права доступа", "", "" ],
    ID            => 'users',
  });

  foreach my $user_line ( @$user_list ) {
    my $delete_button = $html->button("Удалить", "index=$index&DELETE=$user_line->{uid}&sid=$sid", { class => 'del' }) if ($u_role == 3);
    my $block_button = $html->button("заблокировать", "index=$index&DISABLE=$user_line->{uid}&sid=$sid", { class => '_on' });
    
    my $fio = "$user_line->{surname} $user_line->{name} $user_line->{mid_name}";
    my $chg_pswd_button = $html->button("изменить пароль", "index=$index&CHG_PSWD=$user_line->{uid}&sid=$sid", { class => 'password' });
    my $chg_email_button = $html->button($user_line->{email} || "Не указано", "index=$index&CHG_EMAIL=$user_line->{uid}&sid=$sid");
    
    if (!$user_line->{tid}) {
      $table->addrow($user_line->{login}, "Не найдено соответствующего сотрудника", '', '', '', '', $delete_button);
    }
    else {
      my @roles = ("Заблокирован", 
        $html->button("Сотрудник", "index=$index&ROLE_2=$user_line->{uid}&sid=$sid"),
        $html->button("Администратор", "index=$index&ROLE_1=$user_line->{uid}&sid=$sid"),
        "Системный администратор"
      );
      my $chg_role_button = $roles[$user_line->{role}];
      if ($user_line->{role} == 0) {
        $block_button = $html->button("разблокировать", "index=$index&ENABLE=$user_line->{uid}&sid=$sid",  { class => 'off' });  
      }
      $table->addrow($user_line->{login}, $fio, $chg_email_button, $chg_role_button, $chg_pswd_button, $block_button,  $delete_button);
    }
  }

  print $table->show();

  return 1;
}

#**********************************************************
=head2 vacations_emp_list()

=cut
#**********************************************************
sub vacations_emp_list {

  if ($FORM{EMAIL} && $FORM{TID}) {
    my $password = mk_unique_value($conf{PASSWD_LENGTH} || 6, { EXTRA_RULES => '0:0' });
    $User->add({ LOGIN => $FORM{EMAIL}, PASSWORD => $password });
    _error_show($User);

    my $uid = $User->{INSERT_ID};
    
    if ( $User->{errno} ) {
      $html->message('err', "$lang{ERROR}", "Ошибка при создании пользователя $FORM{EMAIL}");
      return 0;
    }

    $User->pi_add({ UID => $uid, EMAIL => $FORM{EMAIL} });
    _error_show($User);

    $Vacations->user_add({ TID => $FORM{TID}, UID => $uid, ROLE => 1 });
    _error_show($Vacations);

    if ($FORM{SEND_EMAIL}) {
      my $message = "LOGIN: $FORM{EMAIL}\nPASSWORD: $password";
      print $html->header();
      sendmail("$conf{ADMIN_MAIL}", "$FORM{EMAIL}", "Password Recovery", "$message", "$conf{MAIL_CHARSET}", "", {TEST => 1});

    }
  }
  elsif ($FORM{USER_ADD}) {
    $html->tpl_show(_include('vacations_user_reg', 'Vacations'), { TID => $FORM{USER_ADD}, %FORM });
  }


  my $emp_list = $Vacations->emp_list();
  my @roles = ("Заблокирован", "Сотрудник", "Администратор", "Системный администратор");
  
  my $table = $html->table({
    width         => '100%',
    caption       => "Список сотрудников",
    border        => 1,
    title_plain   => [ "ФИО", "Табельный номер", "Пользователь"],
    ID            => 'employees',
  });

  foreach my $emp_line ( @$emp_list ) {
    my $fio = "$emp_line->{surname} $emp_line->{name} $emp_line->{mid_name}";
    if ($emp_line->{uid}) {
      $table->addrow($fio, $emp_line->{tid}, $roles[$emp_line->{role}]);
    }
    else {
      my $user_add_button = $html->button("Создать аккаунт", "index=$index&USER_ADD=$emp_line->{tid}&SURNAME=$emp_line->{surname}&sid=$sid", { class => 'btn btn-xs btn-success' });
      $table->addrow($fio, $emp_line->{tid}, $user_add_button);
    }
  }

  print $table->show();

  return 1;
}

#**********************************************************
=head2 _add_years($date, $years)

=cut
#**********************************************************
sub _add_years {
  my ($date, $d_year) = @_;
  my ($year, $month, $day) = split '-', $date;

  $year += $d_year;

  $day = 28 if ($month == 2 && $day == 29 && ($year % 4));

  return sprintf('%04d-%02d-%02d', $year, $month, $day);
}

#**********************************************************
=head2 _add_days($date, $days)

=cut
#**********************************************************
sub _add_days {
  my ($date, $d_days) = @_;
  my ($year, $month, $day) = split '-', $date;
  
  $lastday[1] = ($year % 4) ? 28 : 29;
  $day += $d_days;

  while ($day > $lastday[$month-1]) {
    $day -= $lastday[$month-1];
    $month++;
    if ($month > 12) {
      $year++;
      $month = 1;
      $lastday[1] = ($year % 4) ? 28 : 29;
    }
  }

  while ($day < 1) {
    $month--;
    if ($month == 0) {
      $year--;
      $month = 12;
      $lastday[1] = ($year % 4) ? 28 : 29;
    }
    $day += $lastday[$month-1];
  }


  return sprintf('%04d-%02d-%02d', $year, $month, $day);
}

#**********************************************************
=head2 _period_days($date_start, $date_end)

=cut
#**********************************************************
sub _period_days {
  my ($s_date, $e_date) = @_;
  my ($s_year, $s_month, $s_day) = split '-', $s_date;
  my ($e_year, $e_month, $e_day) = split '-', $e_date;
  
  $lastday[1] = ($e_year % 4) ? 28 : 29;
  
  while ($e_year > $s_year || $e_month > $s_month ) {
    $e_day += $lastday[$e_month];
    $e_month--;
    if ($e_month == 0) {
      $e_year--;
      $e_month = 12;
      $lastday[1] = ($e_year % 4) ? 28 : 29;
    }
  }

  return $e_day - $s_day + 1;
}

1